'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {useCart} from './cart-provider';
import type {CartLine} from '@/types/cart';
import {money} from '@/utils/money';
import {EmptyState,LoadingState,ErrorState,Button} from '@/components/ui';
import {WalletBalance} from '@/components/wallet/wallet-balance';
type Quote={lines:CartLine[];totalCents:number;unavailable:string[];valid:boolean};
export function CartView(){const {items,ready,setQuantity,clear}=useCart();const router=useRouter();const [quote,setQuote]=useState<Quote|null>(null);const [error,setError]=useState('');const [resolvedKey,setResolvedKey]=useState('');const [checkoutLoading,setCheckoutLoading]=useState(false);const requestKey=JSON.stringify(items);const loading=resolvedKey!==requestKey;useEffect(()=>{if(!ready)return;const abort=new AbortController();fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(items),signal:abort.signal}).then(async r=>{if(!r.ok)throw new Error('Não foi possível consultar os produtos.');return r.json();}).then(data=>{if(!abort.signal.aborted){setQuote(data);setError('');}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setResolvedKey(requestKey);});return ()=>abort.abort();},[items,ready,requestKey]);
async function checkout(){setCheckoutLoading(true);setError('');try{const response=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});const data=await response.json();if(response.status===401){router.push('/login?next=/carrinho');return;}if(!response.ok)throw new Error(data.error??'Não foi possível gerar o pagamento PIX.');clear();router.push(data.walletPaid?`/minha-conta/pedidos/${data.orderId}`:`/pagamento/${data.orderId}`);}catch(error){setError(error instanceof Error?error.message:'Não foi possível gerar o pagamento PIX.');setCheckoutLoading(false);}}
if(!ready)return <LoadingState/>;if(!items.length)return <EmptyState title="Seu carrinho está vazio" description="Explore o catálogo e adicione seus produtos favoritos."/>;return <>{error&&<ErrorState message={error}/>}<div aria-busy={loading}>{loading&&<p role="status">Atualizando preços e estoque…</p>}{quote?.lines.map(item=><div className="card row" key={item.productId} style={{marginBottom:12,justifyContent:'space-between'}}><div><Link href={`/produtos/${item.slug}`}><h3>{item.name}</h3></Link><p>{money(item.unitPriceCents)} por unidade</p>{item.quantity>item.availableStock&&<p className="error">Estoque insuficiente ({item.availableStock} disponível).</p>}</div><label>Quantidade<input aria-label={`Quantidade de ${item.name}`} style={{width:85,marginLeft:12}} type="number" min={1} max={99} value={item.quantity} onChange={e=>{const q=Number(e.target.value);if(Number.isInteger(q)&&q>=1)setQuantity(item.productId,q);}}/></label><strong>{money(item.unitPriceCents*item.quantity)}</strong><Button className="secondary" onClick={()=>setQuantity(item.productId,0)}>Remover</Button></div>)}{quote?.unavailable.map(id=><div className="notice" key={id}>Produto indisponível. <button className="text-link" onClick={()=>setQuantity(id,0)}>Remover do carrinho</button></div>)}</div><section className="card stack"><h2>Resumo</h2><WalletBalance/><div className="row">Subtotal <strong>{loading?'Atualizando…':money(quote?.totalCents??0)}</strong></div><div className="row">Total <strong>{loading?'Atualizando…':money(quote?.totalCents??0)}</strong></div><p>Se o saldo disponível cobrir o total, ele será usado automaticamente. Caso contrário, o pagamento será gerado via PIX.</p><Button disabled={loading||checkoutLoading||!quote?.valid} onClick={checkout}>{checkoutLoading?'Processando…':'Continuar para pagamento'}</Button><Button className="secondary" onClick={clear}>Limpar carrinho</Button></section></>;}
