'use server';
import {randomUUID} from 'node:crypto';
import {revalidatePath} from 'next/cache';
import {redirect} from 'next/navigation';
import {requireAdmin} from '@/services/auth/session';
import {db} from '@/lib/db';
import {productSchema,categorySchema} from '@/validations/catalog';
import type {ActionState} from '@/lib/action-state';
import {actionError} from '@/lib/action-error';
import {syncSupplierCatalog} from '@/services/suppliers/supplier.service';
import {fulfillPaidOrder} from '@/services/orders/order.service';
import {uploadImage} from '@/lib/cloudinary';
export async function saveProduct(_:ActionState,form:FormData):Promise<ActionState>{const actor=await requireAdmin();try{const parsed=productSchema.parse(Object.fromEntries(form));const id=String(form.get('id')??'');const fileEntry=form.get('imageFile');const file=fileEntry instanceof File&&fileEntry.size>0?fileEntry:null;const uploaded=file?await uploadImage(file,'revenda-digital/products'):null;await db.$transaction(async tx=>{const data={...parsed,image:uploaded?.url||parsed.image||null};const product=id?await tx.product.update({where:{id},data}):await tx.product.create({data});if(uploaded&&file)await tx.attachment.create({data:{productId:product.id,url:uploaded.url,publicId:uploaded.publicId,filename:file.name,contentType:file.type,bytes:file.size}});await tx.auditLog.create({data:{actorId:actor.id,action:id?'product.updated':'product.created',entityId:product.id}});});}catch(e){return actionError(e);}revalidatePath('/','layout');redirect('/admin/produtos');}
export async function toggleProduct(form:FormData){const actor=await requireAdmin();const id=String(form.get('id'));await db.$transaction(async tx=>{const product=await tx.product.findUniqueOrThrow({where:{id}});await tx.product.update({where:{id},data:{status:product.status==='ACTIVE'?'INACTIVE':'ACTIVE'}});await tx.auditLog.create({data:{actorId:actor.id,action:'product.status.changed',entityId:id}});});revalidatePath('/','layout');}
export async function syncSupplier(_:ActionState,form:FormData){void form;const actor=await requireAdmin();try{const result=await syncSupplierCatalog();await db.auditLog.create({data:{actorId:actor.id,action:'supplier.catalog.synced',metadata:result}});revalidatePath('/','layout');return {success:`Sincronização concluída: ${result.created} criados, ${result.updated} atualizados e ${result.skipped} ignorados.`};}catch(e){return actionError(e);}}
export async function retryOrderDelivery(form:FormData){const actor=await requireAdmin();const orderId=String(form.get('orderId')??'');const order=await db.order.findUnique({where:{id:orderId},select:{id:true,status:true}});if(!order||order.status!=='PROCESSING')throw new Error('Pedido não está aguardando entrega.');await fulfillPaidOrder(order.id);await db.auditLog.create({data:{actorId:actor.id,action:'order.delivery.retried',entityId:order.id}});revalidatePath('/admin/pedidos');revalidatePath('/minha-conta/pedidos');}
export async function toggleCustomer(form:FormData){const actor=await requireAdmin();const id=String(form.get('id')??'');const customer=await db.user.findUniqueOrThrow({where:{id}});if(customer.role!=='CUSTOMER')throw new Error('Somente clientes podem ser suspensos.');const status=customer.status==='ACTIVE'?'SUSPENDED':'ACTIVE';await db.$transaction(async tx=>{await tx.user.update({where:{id},data:{status}});if(status==='SUSPENDED')await tx.session.deleteMany({where:{userId:id}});await tx.auditLog.create({data:{actorId:actor.id,action:`customer.${status.toLowerCase()}`,entityId:id}});});revalidatePath('/admin/clientes');}
export async function creditCustomer(form:FormData){const actor=await requireAdmin();const userId=String(form.get('userId')??'');const amount=Number(form.get('amount'));if(!Number.isFinite(amount)||amount<=0||amount>100000)throw new Error('Informe um crédito válido.');const value=Number(amount.toFixed(2));await db.$transaction(async tx=>{const wallet=await tx.wallet.upsert({where:{userId},create:{userId,balance:value},update:{balance:{increment:value}}});await tx.walletTransaction.create({data:{walletId:wallet.id,type:'ADMIN_CREDIT',amount:value,idempotencyKey:`admin-credit-${actor.id}-${randomUUID()}`}});await tx.auditLog.create({data:{actorId:actor.id,action:'customer.credit.added',entityId:userId,metadata:{amount:value}}});});revalidatePath('/admin/clientes');}
export async function saveCategory(_:ActionState,form:FormData):Promise<ActionState>{const actor=await requireAdmin();try{const data=categorySchema.parse(Object.fromEntries(form));const id=String(form.get('id')??'');await db.$transaction(async tx=>{const category=id?await tx.category.update({where:{id},data}):await tx.category.create({data});await tx.auditLog.create({data:{actorId:actor.id,action:id?'category.updated':'category.created',entityId:category.id}});});revalidatePath('/','layout');return {success:'Categoria salva.'};}catch(e){return actionError(e);}}
export async function deleteCategory(_:ActionState,form:FormData):Promise<ActionState>{const actor=await requireAdmin();try{const id=String(form.get('id'));await db.$transaction(async tx=>{if(await tx.product.count({where:{categoryId:id}}))throw new Error('Esta categoria possui produtos e não pode ser excluída.');await tx.category.delete({where:{id}});await tx.auditLog.create({data:{actorId:actor.id,action:'category.deleted',entityId:id}});});revalidatePath('/','layout');return {success:'Categoria excluída.'};}catch(e){return actionError(e);}}
